AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecsclusternv0
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ecs-log-group
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecs-deployment-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy